nelmio_api_doc:
  documentation:
    info:
      title: Portfolio Backend
      description: API for our portfolio website.
      version: 0.1.0
  areas:
    path_patterns:
      - ^/api(?!/doc|!/doc.json$) # Accepts routes under /api except /api/doc
